import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("./", import.meta.url);

// Sites deploys dist/server/index.js as one ESM Worker module. Inline tools.mjs so the
// published entry has no relative imports that could be missing from the archive.
export async function bundle() {
  const tools = await readFile(new URL("src/tools.mjs", root), "utf8");
  const index = await readFile(new URL("src/index.js", root), "utf8");
  const importLine = "import { tools, upstreamNames } from './tools.mjs';\n";
  if (!index.startsWith(importLine)) throw new Error("src/index.js must start with the tools.mjs import");
  const inlinedTools = tools.replace(/^export (const|function) /gm, "$1 ");
  if (/^export /m.test(inlinedTools)) throw new Error("tools.mjs contains an export the bundler cannot inline");
  return "// Generated by build.mjs: src/tools.mjs + src/index.js\n" + inlinedTools + "\n" + index.slice(importLine.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await mkdir(new URL("dist/server/", root), { recursive: true });
  await mkdir(new URL("dist/.openai/", root), { recursive: true });
  await writeFile(new URL("dist/server/index.js", root), await bundle());
  await copyFile(new URL(".openai/hosting.json", root), new URL("dist/.openai/hosting.json", root));
  console.log("Built dist/server/index.js and dist/.openai/hosting.json");
}
